name: deploy-to-oss
description: upload files to aliyun oss
author: walkthechat
inputs:
  cwd:
    description: change working directory
  accessKeyId:
    required: true
    description: access key you create on aliyun console website
  accessKeySecret:
    required: true
    description: access secret you create
  bucket:
    description: bucket
  region:
    description: region
  endpoint:
    description: oss region domain
  localPath:
    required: true
    description: local path to upload
    default: dist/**/*
  remotePath:
    required: true
    description: remote path
    default: /
  storageClass:
    description: aliyun oss storage class
  objectAcl:
    description: access control
  overwrite:
    description: whether overwrite same name object
  tagging:
    description: tags. TagA&TagB=B

runs:
  using: node16
  main: dist/index.js